---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-templates
  namespace: hub
data:
  login.html: |
    {% extends "templates/login.html" %}

    {% block login %}
    <main id="login-main" class="container">
        <div class="service-login">
            <div class="login-options">
                <div class="box">
                    <span class="large-caption">Log in or create an account here.</span>
                    <p style="margin-top: 30px">
                        <a role="button" style="border-radius: 5px;" class='ms-Button ms-Button--primary'
                            href='{{ authenticator_login_url }}'>
                            <span class="ms-Button-label" style="padding: 20px;">
                                Sign in or Sign up
                            </span>
                        </a>
    </main>

    {% endblock login %}
  spawn.html: |
    {% extends "page.html" %}
    {% if announcement_spawn %}
      {% set announcement = announcement_spawn %}
    {% endif %}

    {% block main %}

    <div class="container">
      {% block heading %}
      <div class="row text-center">
        <h1>Choose your environment</h1>
      </div>
      {% endblock %}
      <div class="row col-sm-offset-2 col-sm-8">
        {% if for_user and user.name != for_user.name -%}
          <p>Spawning server for {{ for_user.name }}</p>
        {% endif -%}
        {% if error_message -%}
          <p class="spawn-error-msg text-danger">
            Error: {{error_message}}
          </p>
        {% endif %}
        <form enctype="multipart/form-data" id="spawn_form" action="{{url}}" method="post" role="form">
          {{spawner_options_form | safe}}
          <br>
          <div class="feedback-container">
            <input type="submit" value="Start" class="btn btn-jupyter form-control">
            <div class="feedback-widget hidden">
              <i class="fa fa-spinner"></i>
            </div>
          </div>
        </form>
      </div>
    </div>

    {% endblock %}

    {% block script %}
    {{ super() }}
    <script>
    // setup onSubmit feedback
    $('form').submit((e) => {
      var form = $(e.target);
      form.find('.feedback-container>input').attr('disabled', true);
      form.find('.feedback-container>*').toggleClass('hidden');
      form.find('.feedback-widget>*').toggleClass('fa-pulse');
    });
    </script>
    {% endblock %}
  page.html: |
    {% extends "templates/page.html" %}

    {% block favicon %}
    <link rel="SHORTCUT ICON" href="https://www.spc.int/sites/default/files/SPC-logo-transparent.png" type="image/x-icon">
    {% endblock %}

    {% block title %} Analytics Hub {% endblock %}

    {% block stylesheet %}
    {{ super() }}
    <script type="module" src="https://unpkg.com/@fluentui/web-components"></script>
    <link rel="stylesheet"
      href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css" />
    <link rel="stylesheet"
      href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.min.css" />
    <link rel="stylesheet"
      href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css" />
    <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js"></script>

    <style>
      body {
        margin: 0;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
          'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
          sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
      }

      .btn {
        border: 1px solid rgb(0, 120, 212);
        background-color: rgb(0, 120, 212);
        color: rgb(255, 255, 255);
      }

      .btn,
      .btn-jupyter {
        border: 1px solid rgb(0, 120, 212);
        background-color: rgb(0, 120, 212);
        color: rgb(255, 255, 255);
      }

      .btn-jupyter.active,
      .btn-jupyter:active,
      .open>.dropdown-toggle.btn-jupyter {
        background-color: #225f8d;
        border-color: #1b4c70;
      }

      .btn-jupyter:hover {
        background-color: #225f8d;
        border-color: #1b4c70;
      }

      .btn-jupyter:focus {
        color: #fff;
        background-color: #225f8d;
        border-color: #1b4c70;
      }

      .btn-jupyter:active .btn-jupyter:focus {
        color: #fff;
        background-color: #225f8d;
        border-color: #1b4c70;
      }

      .btn-jupyter:active:focus {
        color: #fff;
        background-color: #225f8d;
        border-color: #1b4c70;
      }

      .btn.btn-danger {
        color: #fff;
        background-color: #d7191c;
        border-color: #c01619;
      }

      code {
        font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
          monospace;
      }

      p {
        line-height: 1.6;
        margin: 7px 0;
      }

      .large-caption {
        display: block;
        line-height: 1.1;
        font-size: 24px;
        font-weight: 500;
        margin-top: 20px;
        margin-bottom: 10px;
      }

      .layout-container {
        margin: 0 auto;
      }

      .layout-row {
        display: flex;
        flex-flow: row wrap;
        justify-content: flex-start;
      }

      /* All gridded content conforms to these margins */
      @media(min-width: 1080px) {
        .grid-content {
          padding-left: 5% !important;
          padding-right: 5% !important;
        }
      }

      /* Smaller screens ~ tablet size get very small margins */
      @media(max-width: 1079px) {
        .grid-content {
          padding-left: 20px !important;
          padding-right: 20px !important;
        }
      }

      /* Header banner */
      .header-banner {
        background: #F9F9F9;
        min-height: 165px;
        margin-bottom: 40px;
      }

      .banner-item {
        flex-basis: 49%;
        width: 259px;
        position: relative;
        padding-right: 20px;
        box-sizing: border-box;
        display: flex;
        align-items: center;
      }

      .banner-item p {
        font-weight: 500;
      }

      /* Corporate footer styling from UHF */
      header {
        border-bottom: 1px solid rgba(0, 0, 0, .2);
      }

      .grid-content .ms-CommandBar {
        background: rgb(255, 255, 255);
        padding: 3.5px 2px;
        min-height: 57px;
      }

      .site-name {
        font-weight: 600;
        font-size: 18px;
      }

      .c-uhff-base {
        background: #f2f2f2;
        margin: 0 auto;
        padding-top: 5px;
        padding-bottom: 5px;
      }

      .c-uhff-base ul.c-list {
        font-size: 11px;
        line-height: 16px;
        color: #616161;
      }

      .c-list.f-bare {
        padding-left: 0;
        list-style-type: none;
        margin: 11px 0;
      }

      .c-uhff-base ul.c-list li {
        padding: 0 24px 4px 0;
        display: inline-block;
      }

      .context-uhf a:link,
      .context-uhf a:focus,
      .context-uhf a:hover,
      .context-uhf a:active,
      .context-uhf a:visited {
        text-decoration: none;
        color: inherit;
      }

      /* Command Bar overrides */
      .ms-CommandButton-button:active,
      .ms-CommandButton-splitIcon:active {
        background-color: #fff !important;
      }

      .ms-CommandButton:not(:first-of-type) {
        padding-top: 3px;
        margin-left: 1px;
      }

      .grid-content .ms-CommandButton-label:not(.site-name) {
        font-size: 13px;
      }

      .grid-content .ms-CommandButton-button:hover,
      .ms-CommandButton-splitIcon:hover {
        background-color: initial;
      }

      #uhfLogo a:hover {
        text-decoration: none;
      }

      #uhfLogo.ms-CommandButton.ms-CommandButton--pivot.is-active:before,
      #uhfLogo.ms-CommandButton.ms-CommandButton--pivot:hover:before {
        background-color: initial;
      }

      .grid-content .ms-CommandButton.ms-CommandButton--pivot.is-active:before,
      .grid-content .ms-CommandButton.ms-CommandButton--pivot:hover:before {
        background-color: #000;
        margin: 0 7px 7px;
      }

      .grid-content .site-name-cmd {
        padding-top: 1.5px;
        margin-left: -1.5px
      }

      /* JH page styles */
      .container {
        /* Give enough height to the page content to keep the footer at the
              * bottom. In line with the built-in style for login container */
        min-height: 80vh;
      }

      /* Login page styles */
      .box {
        width: 45%;
        padding: 100px;
        border: 1px solid #eaeaea;
        border-radius: 3px;
      }

      .login-options {
        display: flex;
        flex-flow: row wrap;
        justify-content: space-between;
        margin-top: 100px;
      }

      #login-main .service-login {
        vertical-align: top;
      }

      @media(max-width: 768px) {
        .login-options {
          flex-flow: column wrap;
          align-items: center;
          margin-top: 0;
        }

        .box {
          width: 70%;
          padding: 100px;
          margin-bottom: 10px;
        }
      }

      @media(max-width: 555px) {
        .box {
          width: 100%;
          padding: 10px;
          margin-bottom: 10px;
          border: none;
        }

        .banner-item {
          text-align: center;
          flex-basis: 100%;
          justify-content: center;
        }
      }
    </style>
    {% endblock stylesheet %}



    {% block nav_bar %}

    <header class="grid-content">
      <div class="ms-CommandBar ms-CommandBar--navBar" style="height: 100px;">
        <div class="ms-CommandBar-mainArea">
          <span
            style="display: inline-block; font-size: 23.5px; font-weight: 600; margin-top: 3px; margin-right: 6px; margin-left: 22.5px;">|</span>

          <div class="ms-CommandButton ms-CommandButton--pivot site-name-cmd">
            <a class="ms-CommandButton-button" href="https://hub.example.com/">
              <span class="site-name ms-CommandButton-label">
                Digital Earth Analytics Hub
              </span>
            </a>
          </div>
        </div>
      </div>

      <script type="text/javascript">
        var CommandBarElements = document.querySelectorAll(".ms-CommandBar");
        for (var i = 0; i < CommandBarElements.length; i++) {
          new fabric['CommandBar'](CommandBarElements[i]);
        }

        // Address accessibility issues:
        //  <html> must have a lang attribute
        document.querySelector("html").setAttribute("lang", "en");
      </script>
    </header>

    <aside>
      <div class="header-banner layout-row grid-content">
        <div class="banner-item">
          <h1>Analytics Hub</h1>
        </div>
        <div class="banner-item">
          <p>
            This is the <a href="https://example.com">Digital Earth</a> Analytics Hub, 
            a computing environment that allows users to process and analyse massive earth observations datasets.
          </p>
        </div>
      </div>
    </aside>

    {% endblock %}

    {% block footer %}
    <footer class="context-uhf">
      <div class="c-uhff-base grid-content">
        <nav <ul class="c-list f-bare">
          <li class="x-hidden-focus"> © SPC, 2023</li>
          </ul>
        </nav>
      </div>
    </footer>
    {% endblock footer %}
