# A pod that requests a GPU resource.
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-with-gpu
  namespace: hub

spec:
  tolerations:
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: ubuntu
      image: nvidia/cuda:12.6.1-cudnn-devel-ubuntu20.04
      command: ["/bin/sh", "-ec", "sleep 1000"]
      resources:
        limits:
          nvidia.com/gpu: 1
