apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hub
resources:
  - ../../base/jupyterhub
patches:
  - path: jupyterhub-release.yaml
    target:
      kind: HelmRelease
      name: jupyterhub
      namespace: hub
  - path: ingress.yaml
    target:
      kind: HelmRelease
      name: jupyterhub
      namespace: hub
