apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: executor
  namespace: argo
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-workflow-executor-default-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo
roleRef:
  kind: Role
  name: executor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-admin-role
  namespace: argo
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
      - secrets
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - delete
  - apiGroups:
      - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workflows/finalizers
      - workfloweventbindings
      - workfloweventbindings/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - clusterworkflowtemplates
      - clusterworkflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
      - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-workflow-admin-role-binding-argo-read-write-login
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-read-write-login
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-viewer-role
  namespace: argo
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workfloweventbindings
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argo-workflow-viewer-role-binding-argo-default-login
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: argo-default-login
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflow-viewer-role
  apiGroup: rbac.authorization.k8s.io
