apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  valuesFrom:
    - kind: Secret
      name: grafana-values
      valuesKey: values.yaml
      optional: false
  values:
    grafana:
      admin:
        existingSecret: grafana-admin-secret
        userKey: admin-user
        passwordKey: admin-password

      env:
        GF_SERVER_ROOT_URL: https://grafana.prod.example.com/

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/hostname: grafana.prod.example.com
        hosts:
          - grafana.prod.example.com
        tls:
          - hosts:
              - grafana.prod.example.com
            secretName: grafana-ingress

      # grafana.ini:
      #     Contents here are merged in from the secrets created in Terraform
      #     and this is where the DB creds and SSO config lives.
